spring:
  application:
    name: auth-service

    # it must be inside spring

  datasource:
    url: jdbc:postgresql://localhost:5432/ITSoftwareSupport
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    hikari:
      schema: auth_db

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        default_schema: auth_db
        format_sql: true

  flyway:
    enabled: true
    schemas: auth_db
    default-schema: auth_db
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 9091
